check if input file even exists
Signed-off-by: Roland Hieber <r.hieber@pengutronix.de>

diff --git a/spdx-license-match b/spdx-license-match
--- a/spdx-license-match
+++ b/spdx-license-match
@@ -67,6 +67,10 @@ parse_opts() {
 		echo "$SELF: need a file to match"
 		exit 1
 	fi
+	if [ ! -r "$opt_input" ]; then
+		echo "$SELF: unable to read from input"
+		exit 1
+	fi
 }
 
 join_paragraphs() {
